[package]
org = "wso2"
name = "returns_from_sap"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "sap.s4hana.api_customer_returns_delivery_srv_0002"
version = "1.0.0"
repository = "local"
